version: "3.8"

services:
  redis:
    image: redislabs/rejson:latest
    container_name: redis.chatty-backend
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    # command: redis-server --loadmodule "/usr/lib/redis/modules/rejson.so" --requirepass "$REDIS_PASSWORD"

    ports:
      - ${REDIS_PORT}:6379
    networks:
      - global

  mongodb:
    image: mongo
    container_name: mongodb.chatty
    ports:
      - 27017:27017
networks:
  global:
    external: true
